steps:
# This step is useful for debugging when you have issues syncing files with GCP
# - name: gcr.io/cloud-builders/gcloud:latest
#   entrypoint: "ls"
#   args: ["-lah","/workspace"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', '-m', 'rsync', '-d', '-r', 'gs://conall-sandbox-packages', '/workspace/packages/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/conall-sandbox/pypi', '.']
# Is this needed, look deploy.yaml workflow
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/conall-sandbox/pypi']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'pypi', '--image', 'gcr.io/conall-sandbox/pypi', '--port', '80', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
# Docs on why this is needed: https://cloud.google.com/build/docs/build-config#images
images:
- gcr.io/PROJECT_ID/IMAGE
