steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', '-m', 'rsync', '-d', '-r', 'gs://conall-sandbox-packages', 'packages']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/conall-sandbox/pypi', '.']
  
